# Generated by Django 4.1 on 2022-08-18 11:41

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('format', models.CharField(choices=[('V', 'Video'), ('A', 'Audio'), ('D', 'Document')], max_length=1)),
                ('file', models.FileField(upload_to=core.models.content_directory_path)),
                ('json', models.JSONField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
