# Generated by Django 4.1 on 2022-08-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('title', 'format')},
        ),
    ]
