# Generated by Django 4.1 on 2022-08-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_format_content_file_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='json',
            new_name='extra',
        ),
    ]
