# Generated by Django 4.1 on 2022-08-20 10:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_json_content_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='attach_file',
            field=models.FileField(null=True, upload_to=core.models.attach_directory_path),
        ),
    ]
